# Generated by Django 5.2.17 on 2026-09-13 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_experience_description_experience_desc_1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Experience',
            new_name='Organization',
        ),
    ]
