# Generated by Django 5.2.17 on 2026-09-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='logo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
